ln -s ~/dotfiles/scripts ~/.config
ln -s ~/dotfiles/starship.toml ~/.config
ln -s ~/dotfiles/kitty ~/.config
ln -s ~/dotfiles/hypr ~/.config
ln -s ~/dotfiles/wofi ~/.config
ln -s ~/dotfiles/themes ~/.config
ln -s ~/dotfiles/backgrounds ~/config
ln -s ~/dotfiles/waybar ~/.config
ln -s ~/dotfiles/swaylock ~/.config
ln -s ~/dotfiles/wlogout ~/.config
