rm -rf ~/.config/scripts && ln -s ~/dotfiles/scripts ~/.config
rm -rf ~/.config/starship.toml && ln -s ~/dotfiles/starship.toml ~/.config
rm -rf ~/.config/kitty && ln -s ~/dotfiles/kitty ~/.config
rm -rf ~/.config/hypr && ln -s ~/dotfiles/hypr ~/.config
rm -rf ~/.config/wofi && ln -s ~/dotfiles/wofi ~/.config
rm -rf ~/.config/themes && ln -s ~/dotfiles/themes ~/.config
rm -rf ~/.config/backgrounds && ln -s ~/dotfiles/backgrounds ~/.config
rm -rf ~/.config/waybar && ln -s ~/dotfiles/waybar ~/.config
rm -rf ~/.config/xdg-desktop-portal && ln -s ~/dotfiles/xdg-desktop-portal ~/.config
